export const INIT_EDIT_PRODUCT = "INIT_EDIT_PRODUCT";
export const INIT_SELECT_PRODUCT = "INIT_SELECT_PRODUCT";

export const INIT_LOADING_PRODUCTS = "INIT_LOADING_PRODUCTS";
export const FINISH_LOADING_PRODUCTS = "FINISH_LOADING_PRODUCTS";
